use MYM_DB;
go

--CATEGORIA
INSERT INTO CATEGORIA(nombreCategoria)VALUES('Ninguno');
INSERT INTO CATEGORIA(nombreCategoria)VALUES('Mantenimiento');
INSERT INTO CATEGORIA(nombreCategoria)VALUES('Transmicion');
INSERT INTO CATEGORIA(nombreCategoria)VALUES('Frenos');
INSERT INTO CATEGORIA(nombreCategoria)VALUES('Luces');
INSERT INTO CATEGORIA(nombreCategoria)VALUES('Carroceria');
SELECT * FROM CATEGORIA;

--MARCA
INSERT INTO MARCA_PRODUCTO(nombreMarca)VALUES('Ninguno');
INSERT INTO MARCA_PRODUCTO(nombreMarca)VALUES('MYM');
INSERT INTO MARCA_PRODUCTO(nombreMarca)VALUES('Bosch');
INSERT INTO MARCA_PRODUCTO(nombreMarca)VALUES('Denso');
INSERT INTO MARCA_PRODUCTO(nombreMarca)VALUES('Valeo');
INSERT INTO MARCA_PRODUCTO(nombreMarca)VALUES('NGK');
SELECT * FROM MARCA_PRODUCTO;

--PROVEEDOR
INSERT INTO PROVEEDOR(nombreProveedor)VALUES('Ninguno');
INSERT INTO PROVEEDOR(nombreProveedor)VALUES('MYM');
INSERT INTO PROVEEDOR(nombreProveedor)VALUES('Grupo IR');
INSERT INTO PROVEEDOR(nombreProveedor)VALUES('AutoZone');
INSERT INTO PROVEEDOR(nombreProveedor)VALUES('RockAuto');
SELECT * FROM PROVEEDOR;

--VEHICULOS COMPATIBLES
INSERT INTO VEHICULOS_COMPATIBLES(modelo)VALUES('Todos');
INSERT INTO VEHICULOS_COMPATIBLES(modelo)VALUES('Toyota Corolla');
INSERT INTO VEHICULOS_COMPATIBLES(modelo)VALUES('Nissan Sentra');
INSERT INTO VEHICULOS_COMPATIBLES(modelo)VALUES('Kia Picanto');
INSERT INTO VEHICULOS_COMPATIBLES(modelo)VALUES('Toyota RAV4');
INSERT INTO VEHICULOS_COMPATIBLES(modelo)VALUES('Honda Civic');
SELECT * FROM VEHICULOS_COMPATIBLES;
